### ISSUE TITLE
The Template is not working Properly on Zabbix 3.2.7 Based on CentOS 6.9

### ISSUE THREAD

**Issue by debmind** [tsubauaaa/zabbix_aws_integration#1]
Hi, I am facing an issue while using the template. I have followed all the instruction that is given but getting some error at the template, the errors are mentioned below:

Received value [/usr/lib/zabbix/externalscripts/aws_health_dashboard.rb:3:in `require': no such file to load -- nokogiri (LoadError)	from /usr/lib/zabbix/externalscripts/aws_health_dashboard.rb:3] is not suitable for value type [Numeric (unsigned)] and data type [Decimal]

Received value [/usr/lib/zabbix/externalscripts/aws_health_dashboard.rb:3:in `require': no such file to load -- nokogiri (LoadError)	from /usr/lib/zabbix/externalscripts/aws_health_dashboard.rb:3] is not suitable for value type [Numeric (unsigned)] and data type [Decimal]

Received value [/usr/lib/zabbix/externalscripts/get_metric_statistics.rb:20: syntax error, unexpected ':', expecting ')' region: region ^] is not suitable for value type [Numeric (float)]

Received value [/usr/lib/zabbix/externalscripts/get_metric_statistics.rb:20: syntax error, unexpected ':', expecting ')' region: region ^] is not suitable for value type [Numeric (unsigned)] and data type [Decimal]

This kind off error I am getting, please help me to get rid of this, as this is very urgent!

**Comment by tsubauaaa** [comment]
Sorry for the late reply.
Please install nokogiri in the environment where /usr/lib/zabbix/externalscripts/aws_health_dashboard.rb is running. As below.

gem install nokogiri
